import { ROLES } from './roles';

export const PERMISSIONS = {
  // Citizen
  REPORT_WASTE: 'REPORT_WASTE',
  VIEW_OWN_REPORTS: 'VIEW_OWN_REPORTS',
  VIEW_DROP_POINTS: 'VIEW_DROP_POINTS',

  // Worker
  VIEW_ASSIGNED_TASKS: 'VIEW_ASSIGNED_TASKS',
  SCAN_QR: 'SCAN_QR',
  UPDATE_COLLECTION_STATUS: 'UPDATE_COLLECTION_STATUS',

  // Field Officer
  VIEW_WARD_REPORTS: 'VIEW_WARD_REPORTS',
  ASSIGN_WORKERS: 'ASSIGN_WORKERS',
  APPROVE_COLLECTIONS: 'APPROVE_COLLECTIONS',

  // Commissioner Analyst
  VIEW_CITY_ANALYTICS: 'VIEW_CITY_ANALYTICS',
  COMPARE_WARDS: 'COMPARE_WARDS',
  EXPORT_REPORTS: 'EXPORT_REPORTS',

  // Supervisor
  FULL_SYSTEM_ACCESS: 'FULL_SYSTEM_ACCESS'
};

export const ROLE_PERMISSIONS = {
  [ROLES.CITIZEN]: [
    PERMISSIONS.REPORT_WASTE,
    PERMISSIONS.VIEW_OWN_REPORTS,
    PERMISSIONS.VIEW_DROP_POINTS
  ],
  [ROLES.WORKER]: [
    PERMISSIONS.VIEW_ASSIGNED_TASKS,
    PERMISSIONS.SCAN_QR,
    PERMISSIONS.UPDATE_COLLECTION_STATUS,
    PERMISSIONS.VIEW_DROP_POINTS
  ],
  [ROLES.FIELD_OFFICER]: [
    PERMISSIONS.VIEW_WARD_REPORTS,
    PERMISSIONS.ASSIGN_WORKERS,
    PERMISSIONS.APPROVE_COLLECTIONS,
    PERMISSIONS.VIEW_DROP_POINTS
  ],
  [ROLES.COMMISSIONER]: [
    PERMISSIONS.VIEW_CITY_ANALYTICS,
    PERMISSIONS.COMPARE_WARDS,
    PERMISSIONS.EXPORT_REPORTS,
    PERMISSIONS.VIEW_DROP_POINTS
  ],
  [ROLES.SUPERVISOR]: [
    PERMISSIONS.FULL_SYSTEM_ACCESS,
    PERMISSIONS.REPORT_WASTE,
    PERMISSIONS.VIEW_OWN_REPORTS,
    PERMISSIONS.VIEW_DROP_POINTS,
    PERMISSIONS.VIEW_ASSIGNED_TASKS,
    PERMISSIONS.SCAN_QR,
    PERMISSIONS.UPDATE_COLLECTION_STATUS,
    PERMISSIONS.VIEW_WARD_REPORTS,
    PERMISSIONS.ASSIGN_WORKERS,
    PERMISSIONS.APPROVE_COLLECTIONS,
    PERMISSIONS.VIEW_CITY_ANALYTICS,
    PERMISSIONS.COMPARE_WARDS,
    PERMISSIONS.EXPORT_REPORTS
  ]
};
